pagination:
  contests:
    index: 10
    show:
      problems: 10
  problems:
    show:
      submissions: 10
      test_cases: 10

accepted_languages: ['c', 'c++', 'ruby', 'php', 'java', 'python']

problem_ranks: ['E', 'D', 'C', 'B', 'A']
